{
 "title": "My Awesome NodeJS Dashboard",
 "tags": [ "templated" ],
 "refresh": "5s",
 "panels": [
  {
   "title": "CPU Usage (seconds per second)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total[1m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Resident Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    { "expr": "process_resident_memory_bytes", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "HTTP Requests Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum by(status_code, instance) (rate(http_request_duration_seconds_count[1m]))",
     "legendFormat": "{{instance}} - {{status_code}}"
    }
   ]
  },
  {
   "title": "Event Loop Lag",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    { "expr": "nodejs_eventloop_lag_seconds", "legendFormat": "{{instance}}" }
   ]
  }
 ]
}